from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys

from .agent_modelica_v0_8_0_common import (
    DEFAULT_PILOT_PROFILE_OUT_DIR,
    DEFAULT_WORKFLOW_SUBSTRATE_OUT_DIR,
    LEGACY_BUCKET_MAPPING_RATE_MIN,
    REPO_ROOT,
    SCHEMA_PREFIX,
    SPILLOVER_SHARE_MAX,
    UNCLASSIFIED_PENDING_MAX,
    load_json,
    now_utc,
    write_json,
    write_text,
)


def _materialize_artifacts(*, out_root: Path, produced_artifacts: list[str]) -> set[str]:
    produced: set[str] = set()
    for rel_path in produced_artifacts:
        artifact_path = out_root / rel_path
        artifact_path.parent.mkdir(parents=True, exist_ok=True)
        artifact_path.write_text("generated by v0.8.0 pilot profile\n", encoding="utf-8")
        produced.add(rel_path)
    return produced


def _task_scale(row: dict) -> str:
    tier = str(row.get("complexity_tier") or "").strip().lower()
    if tier == "simple":
        return "small"
    if tier == "complex":
        return "large"
    return "medium"


def _task_expected_stage(row: dict) -> str:
    checks = list(row.get("workflow_acceptance_checks") or [])
    if any(str(check.get("type") or "") == "simulate_pass" for check in checks):
        return "simulate"
    return "check"


def _task_failure_type(row: dict) -> str:
    expected_stage = _task_expected_stage(row)
    if expected_stage == "simulate":
        return "simulate_error"
    return "model_check_error"


def _write_fixture(*, row: dict, fixture_dir: Path) -> Path:
    fixture_dir.mkdir(parents=True, exist_ok=True)
    fixture_path = fixture_dir / f"{row['task_id']}.json"
    fixture = row.get("mock_execution_fixture") if isinstance(row.get("mock_execution_fixture"), dict) else {}
    write_json(fixture_path, fixture)
    return fixture_path


def _freeze_taskset(*, rows: list[dict], out_root: Path) -> Path:
    fixture_dir = out_root / "fixtures"
    tasks = []
    for row in rows:
        fixture_path = _write_fixture(row=row, fixture_dir=fixture_dir)
        tasks.append(
            {
                "task_id": row["task_id"],
                "scale": _task_scale(row),
                "failure_type": _task_failure_type(row),
                "expected_stage": _task_expected_stage(row),
                "family_id": row["family_id"],
                "complexity_tier": row["complexity_tier"],
                "live_executor_command": (
                    "python3 -m gateforge.agent_modelica_live_executor_mock_v0 "
                    "--task-id __TASK_ID__ "
                    "--failure-type __FAILURE_TYPE__ "
                    "--expected-stage __EXPECTED_STAGE__ "
                    f"--fixture-path {fixture_path}"
                ),
            }
        )
    taskset_path = out_root / "taskset.json"
    write_json(
        taskset_path,
        {
            "schema_version": f"{SCHEMA_PREFIX}_pilot_taskset",
            "generated_at_utc": now_utc(),
            "tasks": tasks,
        },
    )
    return taskset_path


def _run_gateforge_execution_chain(*, taskset_path: Path, out_root: Path) -> dict:
    run_contract_dir = out_root / "run_contract"
    run_contract_dir.mkdir(parents=True, exist_ok=True)
    summary_path = run_contract_dir / "summary.json"
    results_path = run_contract_dir / "results.json"
    proc = subprocess.run(
        [
            sys.executable,
            "-m",
            "gateforge.agent_modelica_run_contract_v1",
            "--taskset",
            str(taskset_path),
            "--mode",
            "live",
            "--max-rounds",
            "1",
            "--max-time-sec",
            "30",
            "--live-timeout-sec",
            "30",
            "--live-max-output-chars",
            "12000",
            "--results-out",
            str(results_path),
            "--out",
            str(summary_path),
        ],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        check=False,
        timeout=120,
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout or "v0.8.0 run_contract_v1 failed")
    return {
        "summary": load_json(str(summary_path)),
        "results": load_json(str(results_path)),
    }


def _extract_executor_payload(record: dict) -> dict:
    attempts = record.get("attempts") if isinstance(record.get("attempts"), list) else []
    attempts = [item for item in attempts if isinstance(item, dict)]
    payload_text = ""
    if attempts:
        payload_text = str(attempts[-1].get("executor_stdout_tail") or "")
    if not payload_text:
        payload_text = str(record.get("stderr_snippet") or "")
    if not payload_text:
        return {}
    try:
        payload = json.loads(payload_text)
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def _check_passed(check: dict, *, execution_payload: dict, produced_artifacts: set[str]) -> bool:
    check_type = str(check.get("type") or "")
    if check_type == "check_model_pass":
        return bool(execution_payload.get("check_model_pass"))
    if check_type == "simulate_pass":
        return bool(execution_payload.get("simulate_pass"))
    if check_type == "named_result_invariant_pass":
        signal_name = str(check.get("signal_name") or "")
        values = execution_payload.get("signal_values") if isinstance(execution_payload.get("signal_values"), dict) else {}
        if signal_name not in values:
            return False
        value = float(values[signal_name])
        op = str(check.get("comparison_operator") or "")
        if op == "gt":
            return value > float(check.get("threshold"))
        if op == "lt":
            return value < float(check.get("threshold"))
        if op == "between":
            return float(check.get("lower_bound")) <= value <= float(check.get("upper_bound"))
        return False
    if check_type == "expected_goal_artifact_present":
        rel_path = str(check.get("artifact_path") or "")
        return rel_path in produced_artifacts
    return False


def _classify_task(row: dict, *, record: dict, out_root: Path) -> dict:
    execution_payload = _extract_executor_payload(record)
    produced_artifacts = _materialize_artifacts(
        out_root=out_root,
        produced_artifacts=[
            str(item)
            for item in (execution_payload.get("produced_artifacts") or [])
            if str(item or "").strip()
        ],
    )
    execution_payload["produced_artifacts"] = sorted(produced_artifacts)

    checks = list(row.get("workflow_acceptance_checks") or [])
    check_results = {
        f"{idx}:{str(check.get('type') or '')}": _check_passed(
            check,
            execution_payload=execution_payload,
            produced_artifacts=produced_artifacts,
        )
        for idx, check in enumerate(checks, start=1)
    }
    all_checks_pass = all(check_results.values()) if check_results else False
    hard_checks = record.get("hard_checks") if isinstance(record.get("hard_checks"), dict) else {}
    check_model_pass = bool(execution_payload.get("check_model_pass", hard_checks.get("check_model_pass")))
    simulate_pass = bool(execution_payload.get("simulate_pass", hard_checks.get("simulate_pass")))
    base_surface_ok = check_model_pass and simulate_pass
    goal_specific_present = bool(row.get("goal_specific_check_present"))
    legacy_hint = str(row.get("legacy_bucket_hint") or "unclassified_pending_taxonomy")

    if all_checks_pass:
        outcome = "goal_level_resolved"
        goal_alignment = True
        surface_fix_only = False
        legacy_after = "covered_success"
    elif base_surface_ok:
        goal_alignment = legacy_hint != "dispatch_or_policy_limited"
        surface_fix_only = goal_alignment and goal_specific_present
        if surface_fix_only:
            outcome = "surface_fix_only"
            legacy_after = "covered_but_fragile"
        else:
            outcome = "goal_misaligned"
            legacy_after = "dispatch_or_policy_limited"
    else:
        outcome = "unresolved"
        goal_alignment = False
        surface_fix_only = False
        legacy_after = legacy_hint

    return {
        "task_id": row["task_id"],
        "family_id": row["family_id"],
        "complexity_tier": row["complexity_tier"],
        "workflow_task_template_id": row["workflow_task_template_id"],
        "pilot_outcome": outcome,
        "goal_alignment": goal_alignment,
        "surface_fix_only": surface_fix_only,
        "legacy_bucket_after_live_run": legacy_after,
        "goal_specific_check_present": goal_specific_present,
        "execution_source": "gateforge_run_contract_live_path",
        "run_contract_passed": bool(record.get("passed")),
        "execution_payload": execution_payload,
        "acceptance_check_results": check_results,
    }


def build_v080_pilot_workflow_profile(
    *,
    substrate_path: str = str(DEFAULT_WORKFLOW_SUBSTRATE_OUT_DIR / "summary.json"),
    out_dir: str = str(DEFAULT_PILOT_PROFILE_OUT_DIR),
) -> dict:
    substrate = load_json(substrate_path)
    rows = list(substrate.get("task_rows") or [])
    out_root = Path(out_dir)
    taskset_path = _freeze_taskset(rows=rows, out_root=out_root)
    run_payload = _run_gateforge_execution_chain(taskset_path=taskset_path, out_root=out_root)
    records = run_payload.get("results", {}).get("records") if isinstance(run_payload.get("results"), dict) else []
    records_by_task = {
        str(record.get("task_id") or ""): record
        for record in records or []
        if isinstance(record, dict) and str(record.get("task_id") or "").strip()
    }
    case_result_table = [
        _classify_task(
            row,
            record=records_by_task.get(str(row.get("task_id") or ""), {}),
            out_root=out_root,
        )
        for row in rows
    ]
    total = len(case_result_table)

    goal_level_resolved_count = sum(1 for row in case_result_table if row["pilot_outcome"] == "goal_level_resolved")
    surface_fix_only_count = sum(1 for row in case_result_table if row["pilot_outcome"] == "surface_fix_only")
    goal_misaligned_count = sum(1 for row in case_result_table if row["pilot_outcome"] == "goal_misaligned")
    unresolved_count = sum(1 for row in case_result_table if row["pilot_outcome"] == "unresolved")
    goal_alignment_count = sum(1 for row in case_result_table if row["goal_alignment"])
    mapped_count = sum(
        1 for row in case_result_table if row["legacy_bucket_after_live_run"] != "unclassified_pending_taxonomy"
    )
    spillover_count = sum(
        1 for row in case_result_table if row["legacy_bucket_after_live_run"] == "topology_or_open_world_spillover"
    )
    unclassified_count = sum(
        1 for row in case_result_table if row["legacy_bucket_after_live_run"] == "unclassified_pending_taxonomy"
    )

    workflow_resolution_rate_pct = round(goal_level_resolved_count / total * 100, 1)
    goal_alignment_rate_pct = round(goal_alignment_count / total * 100, 1)
    surface_fix_only_rate_pct = round(surface_fix_only_count / total * 100, 1)
    goal_misalignment_rate_pct = round(goal_misaligned_count / total * 100, 1)
    unresolved_rate_pct = round(unresolved_count / total * 100, 1)
    legacy_bucket_mapping_rate_pct = round(mapped_count / total * 100, 1)
    spillover_share_pct = round(spillover_count / total * 100, 1)
    workflow_proximity_delta_vs_v0_7_rate_pct = float(
        substrate.get("workflow_proximity_delta_vs_v0_7_rate_pct") or 0.0
    )

    workflow_resolution_rate_requires_goal_context = surface_fix_only_count > 0 and bool(goal_level_resolved_count)

    payload = {
        "schema_version": f"{SCHEMA_PREFIX}_pilot_workflow_profile",
        "generated_at_utc": now_utc(),
        "status": "PASS"
        if (
            legacy_bucket_mapping_rate_pct >= LEGACY_BUCKET_MAPPING_RATE_MIN
            and spillover_share_pct <= SPILLOVER_SHARE_MAX
            and unclassified_count <= UNCLASSIFIED_PENDING_MAX
        )
        else "FAIL",
        "execution_source": "gateforge_run_contract_live_path",
        "goal_level_oracle_mode": "frozen_executable_oracle",
        "goal_level_resolution_criterion_frozen": True,
        "live_executor_invocation_count": len(records_by_task),
        "workflow_resolution_rate_pct": workflow_resolution_rate_pct,
        "goal_alignment_rate_pct": goal_alignment_rate_pct,
        "surface_fix_only_rate_pct": surface_fix_only_rate_pct,
        "goal_misalignment_rate_pct": goal_misalignment_rate_pct,
        "unresolved_rate_pct": unresolved_rate_pct,
        "legacy_bucket_mapping_rate_pct": legacy_bucket_mapping_rate_pct,
        "spillover_share_pct": spillover_share_pct,
        "unclassified_pending_taxonomy_count": unclassified_count,
        "workflow_proximity_delta_vs_v0_7_rate_pct": workflow_proximity_delta_vs_v0_7_rate_pct,
        "workflow_resolution_rate_requires_goal_context": workflow_resolution_rate_requires_goal_context,
        "run_contract_status": str((run_payload.get("summary") or {}).get("status") or ""),
        "why_not_error_distribution_equivalent": (
            "Goal-level checks change the adjudication outcome: some tasks remove the surface error "
            "but still fail workflow acceptance checks, so they do not count as workflow-level resolution."
        ),
        "case_result_table": case_result_table,
    }
    out_root = Path(out_dir)
    write_json(out_root / "summary.json", payload)
    write_text(
        out_root / "summary.md",
        "\n".join(
            [
                "# v0.8.0 Pilot Workflow Profile",
                "",
                f"- status: `{payload['status']}`",
                f"- workflow_resolution_rate_pct: `{workflow_resolution_rate_pct}`",
                f"- goal_alignment_rate_pct: `{goal_alignment_rate_pct}`",
                f"- surface_fix_only_rate_pct: `{surface_fix_only_rate_pct}`",
                f"- legacy_bucket_mapping_rate_pct: `{legacy_bucket_mapping_rate_pct}`",
                f"- spillover_share_pct: `{spillover_share_pct}`",
            ]
        ),
    )
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the v0.8.0 pilot workflow profile.")
    parser.add_argument(
        "--substrate-path",
        default=str(DEFAULT_WORKFLOW_SUBSTRATE_OUT_DIR / "summary.json"),
    )
    parser.add_argument("--out-dir", default=str(DEFAULT_PILOT_PROFILE_OUT_DIR))
    args = parser.parse_args()
    payload = build_v080_pilot_workflow_profile(
        substrate_path=str(args.substrate_path),
        out_dir=str(args.out_dir),
    )
    print(payload["status"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
