from __future__ import annotations

import argparse
from pathlib import Path

from .agent_modelica_live_executor_mock_v0 import build_payload as build_mock_executor_payload
from .agent_modelica_v0_8_0_common import (
    DEFAULT_PILOT_PROFILE_OUT_DIR,
    DEFAULT_WORKFLOW_SUBSTRATE_OUT_DIR,
    LEGACY_BUCKET_MAPPING_RATE_MIN,
    SCHEMA_PREFIX,
    SPILLOVER_SHARE_MAX,
    UNCLASSIFIED_PENDING_MAX,
    load_json,
    now_utc,
    write_json,
    write_text,
)


def _materialize_artifacts(*, out_root: Path, produced_artifacts: list[str]) -> set[str]:
    produced: set[str] = set()
    for rel_path in produced_artifacts:
        artifact_path = out_root / rel_path
        artifact_path.parent.mkdir(parents=True, exist_ok=True)
        artifact_path.write_text("generated by v0.8.0 pilot profile\n", encoding="utf-8")
        produced.add(rel_path)
    return produced


def _check_passed(check: dict, *, execution_payload: dict, produced_artifacts: set[str]) -> bool:
    check_type = str(check.get("type") or "")
    if check_type == "check_model_pass":
        return bool(execution_payload.get("check_model_pass"))
    if check_type == "simulate_pass":
        return bool(execution_payload.get("simulate_pass"))
    if check_type == "named_result_invariant_pass":
        signal_name = str(check.get("signal_name") or "")
        values = execution_payload.get("signal_values") if isinstance(execution_payload.get("signal_values"), dict) else {}
        if signal_name not in values:
            return False
        value = float(values[signal_name])
        op = str(check.get("comparison_operator") or "")
        if op == "gt":
            return value > float(check.get("threshold"))
        if op == "lt":
            return value < float(check.get("threshold"))
        if op == "between":
            return float(check.get("lower_bound")) <= value <= float(check.get("upper_bound"))
        return False
    if check_type == "expected_goal_artifact_present":
        rel_path = str(check.get("artifact_path") or "")
        return rel_path in produced_artifacts
    return False


def _classify_task(row: dict, *, out_root: Path) -> dict:
    fixture = row.get("mock_execution_fixture") if isinstance(row.get("mock_execution_fixture"), dict) else {}
    execution_payload = build_mock_executor_payload(
        task_id=str(row.get("task_id") or ""),
        failure_type="workflow_proximal_task",
        expected_stage="check",
    )
    execution_payload["check_model_pass"] = bool(fixture.get("check_model_pass"))
    execution_payload["simulate_pass"] = bool(fixture.get("simulate_pass"))
    execution_payload["signal_values"] = fixture.get("signal_values") if isinstance(fixture.get("signal_values"), dict) else {}
    produced_artifacts = _materialize_artifacts(
        out_root=out_root,
        produced_artifacts=list(fixture.get("produced_artifacts") or []),
    )
    execution_payload["produced_artifacts"] = sorted(produced_artifacts)

    checks = list(row.get("workflow_acceptance_checks") or [])
    check_results = {
        f"{idx}:{str(check.get('type') or '')}": _check_passed(
            check,
            execution_payload=execution_payload,
            produced_artifacts=produced_artifacts,
        )
        for idx, check in enumerate(checks, start=1)
    }
    all_checks_pass = all(check_results.values()) if check_results else False
    base_surface_ok = bool(execution_payload.get("check_model_pass")) and bool(execution_payload.get("simulate_pass"))
    goal_specific_present = bool(row.get("goal_specific_check_present"))
    legacy_hint = str(row.get("legacy_bucket_hint") or "unclassified_pending_taxonomy")

    if all_checks_pass:
        outcome = "goal_level_resolved"
        goal_alignment = True
        surface_fix_only = False
        legacy_after = "covered_success"
    elif base_surface_ok:
        goal_alignment = legacy_hint != "dispatch_or_policy_limited"
        surface_fix_only = goal_alignment and goal_specific_present
        if surface_fix_only:
            outcome = "surface_fix_only"
            legacy_after = "covered_but_fragile"
        else:
            outcome = "goal_misaligned"
            legacy_after = "dispatch_or_policy_limited"
    else:
        outcome = "unresolved"
        goal_alignment = False
        surface_fix_only = False
        legacy_after = legacy_hint

    return {
        "task_id": row["task_id"],
        "family_id": row["family_id"],
        "complexity_tier": row["complexity_tier"],
        "workflow_task_template_id": row["workflow_task_template_id"],
        "pilot_outcome": outcome,
        "goal_alignment": goal_alignment,
        "surface_fix_only": surface_fix_only,
        "legacy_bucket_after_live_run": legacy_after,
        "goal_specific_check_present": goal_specific_present,
        "execution_source": "gateforge_agent_mock_execution_path",
        "execution_payload": execution_payload,
        "acceptance_check_results": check_results,
    }


def build_v080_pilot_workflow_profile(
    *,
    substrate_path: str = str(DEFAULT_WORKFLOW_SUBSTRATE_OUT_DIR / "summary.json"),
    out_dir: str = str(DEFAULT_PILOT_PROFILE_OUT_DIR),
) -> dict:
    substrate = load_json(substrate_path)
    rows = list(substrate.get("task_rows") or [])
    out_root = Path(out_dir)
    case_result_table = [_classify_task(row, out_root=out_root) for row in rows]
    total = len(case_result_table)

    goal_level_resolved_count = sum(1 for row in case_result_table if row["pilot_outcome"] == "goal_level_resolved")
    surface_fix_only_count = sum(1 for row in case_result_table if row["pilot_outcome"] == "surface_fix_only")
    goal_misaligned_count = sum(1 for row in case_result_table if row["pilot_outcome"] == "goal_misaligned")
    unresolved_count = sum(1 for row in case_result_table if row["pilot_outcome"] == "unresolved")
    goal_alignment_count = sum(1 for row in case_result_table if row["goal_alignment"])
    mapped_count = sum(
        1 for row in case_result_table if row["legacy_bucket_after_live_run"] != "unclassified_pending_taxonomy"
    )
    spillover_count = sum(
        1 for row in case_result_table if row["legacy_bucket_after_live_run"] == "topology_or_open_world_spillover"
    )
    unclassified_count = sum(
        1 for row in case_result_table if row["legacy_bucket_after_live_run"] == "unclassified_pending_taxonomy"
    )

    workflow_resolution_rate_pct = round(goal_level_resolved_count / total * 100, 1)
    goal_alignment_rate_pct = round(goal_alignment_count / total * 100, 1)
    surface_fix_only_rate_pct = round(surface_fix_only_count / total * 100, 1)
    goal_misalignment_rate_pct = round(goal_misaligned_count / total * 100, 1)
    unresolved_rate_pct = round(unresolved_count / total * 100, 1)
    legacy_bucket_mapping_rate_pct = round(mapped_count / total * 100, 1)
    spillover_share_pct = round(spillover_count / total * 100, 1)
    workflow_proximity_delta_vs_v0_7_rate_pct = float(
        substrate.get("workflow_proximity_delta_vs_v0_7_rate_pct") or 0.0
    )

    workflow_resolution_rate_requires_goal_context = surface_fix_only_count > 0 and bool(goal_level_resolved_count)

    payload = {
        "schema_version": f"{SCHEMA_PREFIX}_pilot_workflow_profile",
        "generated_at_utc": now_utc(),
        "status": "PASS"
        if (
            legacy_bucket_mapping_rate_pct >= LEGACY_BUCKET_MAPPING_RATE_MIN
            and spillover_share_pct <= SPILLOVER_SHARE_MAX
            and unclassified_count <= UNCLASSIFIED_PENDING_MAX
        )
        else "FAIL",
        "execution_source": "gateforge_agent_mock_execution_path",
        "goal_level_oracle_mode": "frozen_executable_oracle",
        "goal_level_resolution_criterion_frozen": True,
        "live_executor_invocation_count": total,
        "workflow_resolution_rate_pct": workflow_resolution_rate_pct,
        "goal_alignment_rate_pct": goal_alignment_rate_pct,
        "surface_fix_only_rate_pct": surface_fix_only_rate_pct,
        "goal_misalignment_rate_pct": goal_misalignment_rate_pct,
        "unresolved_rate_pct": unresolved_rate_pct,
        "legacy_bucket_mapping_rate_pct": legacy_bucket_mapping_rate_pct,
        "spillover_share_pct": spillover_share_pct,
        "unclassified_pending_taxonomy_count": unclassified_count,
        "workflow_proximity_delta_vs_v0_7_rate_pct": workflow_proximity_delta_vs_v0_7_rate_pct,
        "workflow_resolution_rate_requires_goal_context": workflow_resolution_rate_requires_goal_context,
        "why_not_error_distribution_equivalent": (
            "Goal-level checks change the adjudication outcome: some tasks remove the surface error "
            "but still fail workflow acceptance checks, so they do not count as workflow-level resolution."
        ),
        "case_result_table": case_result_table,
    }
    out_root = Path(out_dir)
    write_json(out_root / "summary.json", payload)
    write_text(
        out_root / "summary.md",
        "\n".join(
            [
                "# v0.8.0 Pilot Workflow Profile",
                "",
                f"- status: `{payload['status']}`",
                f"- workflow_resolution_rate_pct: `{workflow_resolution_rate_pct}`",
                f"- goal_alignment_rate_pct: `{goal_alignment_rate_pct}`",
                f"- surface_fix_only_rate_pct: `{surface_fix_only_rate_pct}`",
                f"- legacy_bucket_mapping_rate_pct: `{legacy_bucket_mapping_rate_pct}`",
                f"- spillover_share_pct: `{spillover_share_pct}`",
            ]
        ),
    )
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the v0.8.0 pilot workflow profile.")
    parser.add_argument(
        "--substrate-path",
        default=str(DEFAULT_WORKFLOW_SUBSTRATE_OUT_DIR / "summary.json"),
    )
    parser.add_argument("--out-dir", default=str(DEFAULT_PILOT_PROFILE_OUT_DIR))
    args = parser.parse_args()
    payload = build_v080_pilot_workflow_profile(
        substrate_path=str(args.substrate_path),
        out_dir=str(args.out_dir),
    )
    print(payload["status"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
