#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="${GATEFORGE_AGENT_UNKNOWN_LIBRARY_LIVE_EVIDENCE_OUT_DIR:-artifacts/agent_modelica_unknown_library_live_evidence_v1}"
RUN_ID="${GATEFORGE_AGENT_UNKNOWN_LIBRARY_RESUME_RUN_ID:-${GATEFORGE_AGENT_UNKNOWN_LIBRARY_RUN_ID:-}}"
RUN_ROOT="${GATEFORGE_AGENT_UNKNOWN_LIBRARY_RESUME_RUN_ROOT:-${GATEFORGE_AGENT_UNKNOWN_LIBRARY_RUN_ROOT:-}}"
STAGES="${GATEFORGE_AGENT_UNKNOWN_LIBRARY_RESUME_STAGES:-auto}"
UPDATE_LATEST="${GATEFORGE_AGENT_UNKNOWN_LIBRARY_UPDATE_LATEST:-1}"
FORCE_RERUN_COMPLETED="${GATEFORGE_AGENT_UNKNOWN_LIBRARY_FORCE_RERUN_COMPLETED:-0}"

export GATEFORGE_AGENT_UNKNOWN_LIBRARY_RESUME=1
export GATEFORGE_AGENT_UNKNOWN_LIBRARY_LIVE_EVIDENCE_OUT_DIR="$OUT_DIR"
export GATEFORGE_AGENT_UNKNOWN_LIBRARY_RUN_ID="$RUN_ID"
export GATEFORGE_AGENT_UNKNOWN_LIBRARY_RUN_ROOT="$RUN_ROOT"
export GATEFORGE_AGENT_UNKNOWN_LIBRARY_RESUME_STAGES="$STAGES"
export GATEFORGE_AGENT_UNKNOWN_LIBRARY_UPDATE_LATEST="$UPDATE_LATEST"
export GATEFORGE_AGENT_UNKNOWN_LIBRARY_FORCE_RERUN_COMPLETED="$FORCE_RERUN_COMPLETED"

bash scripts/run_agent_modelica_unknown_library_live_evidence_v1.sh
