#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="${GATEFORGE_AGENT_LIVE_ROUND_OUT_DIR:-artifacts/agent_modelica_live_round_v1}"
WEEK_TAG="${GATEFORGE_AGENT_LIVE_WEEK_TAG:-live-$(date -u +%Y%m%dT%H%M%SZ)}"
PROFILE_PATH="${GATEFORGE_AGENT_MVP_PROFILE_PATH:-benchmarks/agent_modelica_mvp_repair_v1.json}"
LIVE_EXECUTOR_CMD="${GATEFORGE_AGENT_LIVE_EXECUTOR_CMD:-}"
LIVE_TIMEOUT_SEC="${GATEFORGE_AGENT_LIVE_TIMEOUT_SEC:-240}"
LIVE_MAX_OUTPUT_CHARS="${GATEFORGE_AGENT_LIVE_MAX_OUTPUT_CHARS:-2400}"
ALLOW_BASELINE_FAIL="${GATEFORGE_AGENT_ALLOW_BASELINE_FAIL:-1}"

if [ -z "$LIVE_EXECUTOR_CMD" ]; then
  echo "missing GATEFORGE_AGENT_LIVE_EXECUTOR_CMD for live mode" >&2
  exit 1
fi

GATEFORGE_AGENT_MVP_PROFILE_PATH="$PROFILE_PATH" \
GATEFORGE_AGENT_WEEKLY_CHAIN_OUT_DIR="$OUT_DIR" \
GATEFORGE_AGENT_WEEK_TAG="$WEEK_TAG" \
GATEFORGE_AGENT_RUN_MODE="live" \
GATEFORGE_AGENT_LIVE_EXECUTOR_CMD="$LIVE_EXECUTOR_CMD" \
GATEFORGE_AGENT_LIVE_TIMEOUT_SEC="$LIVE_TIMEOUT_SEC" \
GATEFORGE_AGENT_LIVE_MAX_OUTPUT_CHARS="$LIVE_MAX_OUTPUT_CHARS" \
GATEFORGE_AGENT_ALLOW_BASELINE_FAIL="$ALLOW_BASELINE_FAIL" \
bash scripts/run_agent_modelica_weekly_chain_v1.sh
