#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="${GATEFORGE_AGENT_LIVE_ROUND_OUT_DIR:-artifacts/agent_modelica_live_round_v1}"
WEEK_TAG="${GATEFORGE_AGENT_LIVE_WEEK_TAG:-live-$(date -u +%Y%m%dT%H%M%SZ)}"
PROFILE_PATH="${GATEFORGE_AGENT_MVP_PROFILE_PATH:-benchmarks/agent_modelica_mvp_repair_v1.json}"
DEFAULT_LIVE_EXECUTOR_CMD="python3 -m gateforge.agent_modelica_live_executor_gemini_v1 --task-id \"__TASK_ID__\" --failure-type \"__FAILURE_TYPE__\" --expected-stage \"__EXPECTED_STAGE__\" --source-model-path \"__SOURCE_MODEL_PATH__\" --mutated-model-path \"__MUTATED_MODEL_PATH__\" --repair-actions \"__REPAIR_ACTIONS_JSON__\" --max-rounds \"__MAX_ROUNDS__\" --timeout-sec \"__MAX_TIME_SEC__\" --planner-backend \"${GATEFORGE_AGENT_LIVE_PLANNER_BACKEND:-gemini}\" --backend \"${GATEFORGE_AGENT_LIVE_OM_BACKEND:-auto}\" --docker-image \"${GATEFORGE_AGENT_LIVE_OM_DOCKER_IMAGE:-openmodelica/openmodelica:v1.26.1-minimal}\""
LIVE_EXECUTOR_CMD="${GATEFORGE_AGENT_LIVE_EXECUTOR_CMD:-$DEFAULT_LIVE_EXECUTOR_CMD}"
LIVE_TIMEOUT_SEC="${GATEFORGE_AGENT_LIVE_TIMEOUT_SEC:-240}"
LIVE_MAX_OUTPUT_CHARS="${GATEFORGE_AGENT_LIVE_MAX_OUTPUT_CHARS:-2400}"
ALLOW_BASELINE_FAIL="${GATEFORGE_AGENT_ALLOW_BASELINE_FAIL:-1}"

GATEFORGE_AGENT_MVP_PROFILE_PATH="$PROFILE_PATH" \
GATEFORGE_AGENT_WEEKLY_CHAIN_OUT_DIR="$OUT_DIR" \
GATEFORGE_AGENT_WEEK_TAG="$WEEK_TAG" \
GATEFORGE_AGENT_RUN_MODE="live" \
GATEFORGE_AGENT_LIVE_EXECUTOR_CMD="$LIVE_EXECUTOR_CMD" \
GATEFORGE_AGENT_LIVE_TIMEOUT_SEC="$LIVE_TIMEOUT_SEC" \
GATEFORGE_AGENT_LIVE_MAX_OUTPUT_CHARS="$LIVE_MAX_OUTPUT_CHARS" \
GATEFORGE_AGENT_ALLOW_BASELINE_FAIL="$ALLOW_BASELINE_FAIL" \
bash scripts/run_agent_modelica_weekly_chain_v1.sh
